---


  tags:
    - grafana_pkg

- name: Create Grafana config file
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_sysconfig_conf_file }}"
  notify:
    - Restart Grafana
  tags:
    - grafana_config

- name: Create LDAP config file
  template:
    src: ldap.toml.j2
    dest: "{{ grafana_sysconfig_conf_dir ~ '/ldap.toml' }}"
  notify:
    - Restart Grafana
  tags:
    - grafana_config

- name: Check if the binary can bind to TCP port <1024
  shell: getcap /usr/sbin/grafana-server | grep cap_net_bind_service
  register: grafana_bind_cap
  failed_when: False
  changed_when: False
  when: grafana_allow_low_port
  tags:
    - grafana_config

- name: Set capability on the binary file to be able to bind to TCP port <1024
  shell: setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server
  when: grafana_allow_low_port and grafana_bind_cap.rc > 0
  notify:
    - Restart Grafana
  tags:
    - grafana_config

- name: Enable the Grafana service
  service:
    name: "{{ grafana_service }}"
    enabled: yes
  tags:
    - grafana_service

- name: Start the Grafana service
  service:
    name: "{{ grafana_service }}"
    state: running
  register: grafana_service_started
  tags:
    - grafana_service
